2022-04-24 18:28:01,426 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 3 hosts
2022-04-24 18:28:07,255 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 3 hosts
2022-04-24 18:29:07,503 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 3 hosts
2022-04-24 18:29:21,508 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 3 hosts
2022-04-24 18:34:25,205 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 3 hosts
2022-04-24 18:34:25,211 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 2 hosts
2022-04-24 18:37:10,427 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-04-24 18:37:10,435 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 4 hosts
2022-04-24 18:37:39,025 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-04-24 18:37:39,034 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 4 hosts
2022-04-24 18:41:27,661 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-04-24 18:41:45,072 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-04-24 18:42:27,495 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-04-24 18:42:27,503 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 4 hosts
2022-04-24 18:42:35,011 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-04-24 18:42:35,020 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 4 hosts
2022-04-24 18:43:08,394 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-04-24 18:43:08,403 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 1 hosts
2022-04-24 18:43:27,175 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-04-24 18:43:27,183 -  nornir.core -  WARNING -        run() - Task 'hello_world' has not been run â€“ 0 hosts selected
2022-04-24 18:43:32,951 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-04-24 18:43:32,958 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 2 hosts
2022-04-24 18:44:05,125 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-04-24 18:44:05,135 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 2 hosts
2022-04-24 18:44:11,928 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-04-24 18:44:11,937 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 2 hosts
2022-04-24 18:44:21,517 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 2 hosts
2022-04-24 18:44:26,153 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 2 hosts
2022-04-24 18:44:34,093 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 4 hosts
2022-04-24 18:49:04,576 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ip int br']} on 4 hosts
2022-04-24 18:49:04,626 - nornir.core.task -    ERROR -      start() - Host 'R1-CPE-BAT-B': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/client.py", line 368, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 172.16.100.189

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/base/base.py", line 86, in _netmiko_open
    self._netmiko_device = ConnectHandler(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/cisco/cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 350, in __init__
    self._open()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 355, in _open
    self.establish_connection()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 957, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 172.16.100.189:22



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/connections/__init__.py", line 57, in open
    connection.open()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 169, in open
    self.device = self._netmiko_open(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/base/base.py", line 95, in _netmiko_open
    raise ConnectionException("Cannot connect to {}".format(self.hostname))
napalm.base.exceptions.ConnectionException: Cannot connect to 172.16.100.189

2022-04-24 18:49:04,628 - nornir.core.task -    ERROR -      start() - Host 'R2-CPE-BAT-B': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/client.py", line 368, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 172.16.100.190

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/base/base.py", line 86, in _netmiko_open
    self._netmiko_device = ConnectHandler(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/cisco/cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 350, in __init__
    self._open()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 355, in _open
    self.establish_connection()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 957, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 172.16.100.190:22



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/connections/__init__.py", line 57, in open
    connection.open()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 169, in open
    self.device = self._netmiko_open(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/base/base.py", line 95, in _netmiko_open
    raise ConnectionException("Cannot connect to {}".format(self.hostname))
napalm.base.exceptions.ConnectionException: Cannot connect to 172.16.100.190

2022-04-24 18:53:00,674 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ip int br']} on 4 hosts
2022-04-24 18:54:18,126 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['arp_table']} on 6 hosts
2022-04-24 18:54:45,489 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['arp_table']} on 2 hosts
2022-04-24 18:58:57,355 -  nornir.core -  WARNING -        run() - Task 'napalm_configure' has not been run â€“ 0 hosts selected
2022-04-24 18:58:57,357 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': 'int loopback 1\n ip add 2.2.2.2 255.255.255.255'} on 1 hosts
2022-04-24 18:59:59,805 -  nornir.core -  WARNING -        run() - Task 'napalm_configure' has not been run â€“ 0 hosts selected
2022-04-24 18:59:59,807 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': 'int loopback 1\n ip add 2.2.2.2 255.255.255.255'} on 1 hosts
2022-04-24 19:01:02,031 -  nornir.core -  WARNING -        run() - Task 'napalm_configure' has not been run â€“ 0 hosts selected
2022-04-24 19:01:02,033 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': 'int loopback 1\n ip add 2.2.2.2 255.255.255.255'} on 1 hosts
2022-04-24 19:01:55,034 -  nornir.core -  WARNING -        run() - Task 'napalm_configure' has not been run â€“ 0 hosts selected
2022-04-24 19:02:20,801 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': 'int loopback 1\n ip add 1.1.1.1 255.255.255.255'} on 1 hosts
2022-04-24 19:04:27,578 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['write']} on 6 hosts
2022-04-24 19:08:34,226 -  nornir.core -  WARNING -        run() - Task 'netmiko_send_command' has not been run â€“ 0 hosts selected
2022-04-24 19:09:27,080 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show ip int br'} on 3 hosts
2022-04-24 19:09:44,382 -  nornir.core -  WARNING -        run() - Task 'netmiko_send_command' has not been run â€“ 0 hosts selected
2022-04-24 19:12:14,252 -  nornir.core -  WARNING -        run() - Task 'netmiko_send_command' has not been run â€“ 0 hosts selected
2022-04-24 19:12:31,396 -  nornir.core -  WARNING -        run() - Task 'netmiko_send_command' has not been run â€“ 0 hosts selected
2022-04-24 19:15:14,887 -  nornir.core -  WARNING -        run() - Task 'netmiko_send_command' has not been run â€“ 0 hosts selected
2022-04-24 19:15:24,071 -  nornir.core -  WARNING -        run() - Task 'netmiko_send_command' has not been run â€“ 0 hosts selected
2022-04-24 19:16:28,356 -  nornir.core -  WARNING -        run() - Task 'netmiko_send_command' has not been run â€“ 0 hosts selected
2022-04-24 19:16:38,533 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show ip int br'} on 4 hosts
2022-04-24 19:21:39,533 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show ip int br'} on 4 hosts
2022-04-24 19:21:57,438 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['int loopback 1', 'ip add 1.1.1.2 255.255.255.255']} on 1 hosts
2022-04-24 19:21:58,314 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['int loopback 1', 'ip add 2.2.2.3 255.255.255.255']} on 1 hosts
2022-04-24 19:23:11,646 -  nornir.core -     INFO -        run() - Running task 'netmiko_save_config' with args {} on 1 hosts
2022-04-24 19:23:12,867 -  nornir.core -     INFO -        run() - Running task 'netmiko_save_config' with args {} on 1 hosts
2022-04-24 19:30:41,295 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/ESW1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-04-24 19:32:01,238 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-04-24 19:32:02,746 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R2_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-04-24 19:32:08,223 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/ESW1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-04-24 19:36:39,944 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-04-24 19:36:41,296 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R2_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-04-24 19:36:46,345 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/ESW1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-04-24 19:36:54,702 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:36:55,483 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R2_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:36:59,569 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/ESW1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:37:35,476 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-04-24 19:37:36,906 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R2_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-04-24 19:37:41,631 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/ESW1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-04-24 19:37:49,646 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:37:52,835 - nornir.core.task -    ERROR -      start() - Host 'R1-CPE-BAT-B': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 40, in netmiko_send_config
    result = net_connect.send_config_from_file(config_file=config_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1809, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1921, in send_config_set
    new_output = self.read_until_pattern(pattern=pattern)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 575, in _read_channel_expect
    raise EOFError("Channel stream closed by remote device.")
EOFError: Channel stream closed by remote device.

2022-04-24 19:37:52,844 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R2_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:37:56,338 - nornir.core.task -    ERROR -      start() - Host 'R2-CPE-BAT-B': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 40, in netmiko_send_config
    result = net_connect.send_config_from_file(config_file=config_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1809, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1921, in send_config_set
    new_output = self.read_until_pattern(pattern=pattern)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 575, in _read_channel_expect
    raise EOFError("Channel stream closed by remote device.")
EOFError: Channel stream closed by remote device.

2022-04-24 19:37:56,347 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/ESW1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:39:38,290 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-04-24 19:39:39,777 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R2_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-04-24 19:39:44,999 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/ESW1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-04-24 19:40:52,676 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:40:56,082 - nornir.core.task -    ERROR -      start() - Host 'R1-CPE-BAT-B': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 40, in netmiko_send_config
    result = net_connect.send_config_from_file(config_file=config_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1809, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1921, in send_config_set
    new_output = self.read_until_pattern(pattern=pattern)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 575, in _read_channel_expect
    raise EOFError("Channel stream closed by remote device.")
EOFError: Channel stream closed by remote device.

2022-04-24 19:40:56,085 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R2_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:40:59,447 - nornir.core.task -    ERROR -      start() - Host 'R2-CPE-BAT-B': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 40, in netmiko_send_config
    result = net_connect.send_config_from_file(config_file=config_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1809, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1921, in send_config_set
    new_output = self.read_until_pattern(pattern=pattern)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 575, in _read_channel_expect
    raise EOFError("Channel stream closed by remote device.")
EOFError: Channel stream closed by remote device.

2022-04-24 19:40:59,457 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/ESW1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:42:10,884 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:42:14,124 - nornir.core.task -    ERROR -      start() - Host 'R1-CPE-BAT-B': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 40, in netmiko_send_config
    result = net_connect.send_config_from_file(config_file=config_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1809, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1912, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 575, in _read_channel_expect
    raise EOFError("Channel stream closed by remote device.")
EOFError: Channel stream closed by remote device.

2022-04-24 19:42:14,130 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R2_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:42:17,739 - nornir.core.task -    ERROR -      start() - Host 'R2-CPE-BAT-B': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 40, in netmiko_send_config
    result = net_connect.send_config_from_file(config_file=config_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1809, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1912, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 575, in _read_channel_expect
    raise EOFError("Channel stream closed by remote device.")
EOFError: Channel stream closed by remote device.

2022-04-24 19:42:17,748 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/ESW1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:43:36,491 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:43:39,667 - nornir.core.task -    ERROR -      start() - Host 'R1-CPE-BAT-B': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 40, in netmiko_send_config
    result = net_connect.send_config_from_file(config_file=config_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1809, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1921, in send_config_set
    new_output = self.read_until_pattern(pattern=pattern)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 575, in _read_channel_expect
    raise EOFError("Channel stream closed by remote device.")
EOFError: Channel stream closed by remote device.

2022-04-24 19:43:39,677 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R2_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:43:42,903 - nornir.core.task -    ERROR -      start() - Host 'R2-CPE-BAT-B': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 40, in netmiko_send_config
    result = net_connect.send_config_from_file(config_file=config_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1809, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1921, in send_config_set
    new_output = self.read_until_pattern(pattern=pattern)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 575, in _read_channel_expect
    raise EOFError("Channel stream closed by remote device.")
EOFError: Channel stream closed by remote device.

2022-04-24 19:43:42,915 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/ESW1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:45:42,503 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:45:45,848 - nornir.core.task -    ERROR -      start() - Host 'R1-CPE-BAT-B': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 40, in netmiko_send_config
    result = net_connect.send_config_from_file(config_file=config_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1809, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1912, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 575, in _read_channel_expect
    raise EOFError("Channel stream closed by remote device.")
EOFError: Channel stream closed by remote device.

2022-04-24 19:46:01,657 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:46:33,473 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:46:36,742 - nornir.core.task -    ERROR -      start() - Host 'R1-CPE-BAT-B': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 40, in netmiko_send_config
    result = net_connect.send_config_from_file(config_file=config_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1809, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1921, in send_config_set
    new_output = self.read_until_pattern(pattern=pattern)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 575, in _read_channel_expect
    raise EOFError("Channel stream closed by remote device.")
EOFError: Channel stream closed by remote device.

2022-04-24 19:46:48,044 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:46:52,045 - nornir.core.task -    ERROR -      start() - Host 'R1-CPE-BAT-B': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 40, in netmiko_send_config
    result = net_connect.send_config_from_file(config_file=config_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1809, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1912, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 575, in _read_channel_expect
    raise EOFError("Channel stream closed by remote device.")
EOFError: Channel stream closed by remote device.

2022-04-24 19:47:58,963 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:48:16,522 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R2_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:50:25,874 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R2_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:51:20,559 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-04-24 19:52:26,917 -  nornir.core -     INFO -        run() - Running task 'netmiko_save_config' with args {} on 6 hosts
2022-04-24 19:58:35,363 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['router ospf 1', 'network 172.16.10.0 0.0.0.255 area 0', 'network 172.16.20.0 0.0.0.255 area 0']} on 1 hosts
2022-04-24 19:58:36,218 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['router ospf 1', 'network 172.16.10.0 0.0.0.255 area 0', 'network 172.16.20.0 0.0.0.255 area 0']} on 1 hosts
2022-04-24 19:58:38,282 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['router ospf 1', 'network 172.16.30.0 0.0.0.255 area 0', 'network 172.16.40.0 0.0.0.255 area 0']} on 1 hosts
2022-04-24 19:58:38,459 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['router ospf 1', 'network 172.16.30.0 0.0.0.255 area 0', 'network 172.16.40.0 0.0.0.255 area 0']} on 1 hosts
2022-04-24 19:58:39,368 -  nornir.core -     INFO -        run() - Running task 'netmiko_save_config' with args {} on 6 hosts
2022-04-24 19:59:22,768 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['router ospf 1', 'network 172.16.10.0 0.0.0.255 area 0', 'network 172.16.20.0 0.0.0.255 area 0']} on 1 hosts
2022-04-24 19:59:23,579 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['router ospf 1', 'network 172.16.10.0 0.0.0.255 area 0', 'network 172.16.20.0 0.0.0.255 area 0']} on 1 hosts
2022-04-24 19:59:25,008 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['router ospf 1', 'network 172.16.30.0 0.0.0.255 area 0', 'network 172.16.40.0 0.0.0.255 area 0']} on 1 hosts
2022-04-24 19:59:27,662 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['router ospf 1', 'network 172.16.30.0 0.0.0.255 area 0', 'network 172.16.40.0 0.0.0.255 area 0']} on 1 hosts
2022-04-24 19:59:30,423 -  nornir.core -     INFO -        run() - Running task 'netmiko_save_config' with args {} on 6 hosts
2022-05-09 14:36:56,333 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-05-09 14:42:00,445 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-05-09 14:47:23,731 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-05-09 14:47:34,244 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-05-09 14:47:44,138 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-05-09 14:47:49,864 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-05-09 14:47:57,512 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-05-09 14:48:16,024 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-05-09 14:48:24,055 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-05-09 14:48:53,341 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-05-09 14:49:03,585 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-05-09 14:59:16,580 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-05-10 08:41:55,520 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-05-10 09:08:00,291 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 2 hosts
2022-05-10 09:49:57,028 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2022-05-10 11:10:03,399 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['sh ip int brief']} on 4 hosts
2022-05-10 11:37:43,570 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 2 hosts
2022-05-10 11:55:11,294 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 2 hosts
2022-05-10 12:01:08,423 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': ['interface loopback 1 R1: 1.1.1.1 255.255.255.255']} on 6 hosts
2022-05-10 12:01:09,341 - nornir.core.task -    ERROR -      start() - Host 'R1-CPE-BAT-A': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 269, in _load_candidate_wrapper
    tmp_file = self._create_tmp_file(source_config)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 244, in _create_tmp_file
    fobj.write(config)
TypeError: write() argument must be str, not list

2022-05-10 12:01:10,831 - nornir.core.task -    ERROR -      start() - Host 'ESW1-CPE-BAT-A': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 269, in _load_candidate_wrapper
    tmp_file = self._create_tmp_file(source_config)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 244, in _create_tmp_file
    fobj.write(config)
TypeError: write() argument must be str, not list

2022-05-10 12:01:11,238 - nornir.core.task -    ERROR -      start() - Host 'R2-CPE-BAT-A': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 269, in _load_candidate_wrapper
    tmp_file = self._create_tmp_file(source_config)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 244, in _create_tmp_file
    fobj.write(config)
TypeError: write() argument must be str, not list

2022-05-10 12:01:11,339 - nornir.core.task -    ERROR -      start() - Host 'ESW1-CPE-BAT-B': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 269, in _load_candidate_wrapper
    tmp_file = self._create_tmp_file(source_config)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 244, in _create_tmp_file
    fobj.write(config)
TypeError: write() argument must be str, not list

2022-05-10 12:01:11,521 - nornir.core.task -    ERROR -      start() - Host 'R1-CPE-BAT-B': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 269, in _load_candidate_wrapper
    tmp_file = self._create_tmp_file(source_config)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 244, in _create_tmp_file
    fobj.write(config)
TypeError: write() argument must be str, not list

2022-05-10 12:01:11,574 - nornir.core.task -    ERROR -      start() - Host 'R2-CPE-BAT-B': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 269, in _load_candidate_wrapper
    tmp_file = self._create_tmp_file(source_config)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 244, in _create_tmp_file
    fobj.write(config)
TypeError: write() argument must be str, not list

2022-05-10 12:01:11,587 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': ['interface loopback 1 R2: 2.2.2.2 255.255.255.255']} on 6 hosts
2022-05-10 12:08:12,142 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': ['interface loopback 1', 'ip address 1.1.1.1 255.255.255.255']} on 1 hosts
2022-05-10 12:08:12,978 - nornir.core.task -    ERROR -      start() - Host 'R1-CPE-BAT-A': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 269, in _load_candidate_wrapper
    tmp_file = self._create_tmp_file(source_config)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 244, in _create_tmp_file
    fobj.write(config)
TypeError: write() argument must be str, not list

2022-05-10 12:08:12,984 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': ['interface loopback 1', 'ip address 2.2.2.2 255.255.255.255']} on 1 hosts
2022-05-10 12:08:14,613 - nornir.core.task -    ERROR -      start() - Host 'R2-CPE-BAT-A': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 269, in _load_candidate_wrapper
    tmp_file = self._create_tmp_file(source_config)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 244, in _create_tmp_file
    fobj.write(config)
TypeError: write() argument must be str, not list

2022-05-10 12:08:33,216 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': ['interface loopback 1 ip address 1.1.1.1 255.255.255.255']} on 1 hosts
2022-05-10 12:08:34,032 - nornir.core.task -    ERROR -      start() - Host 'R1-CPE-BAT-A': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 269, in _load_candidate_wrapper
    tmp_file = self._create_tmp_file(source_config)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 244, in _create_tmp_file
    fobj.write(config)
TypeError: write() argument must be str, not list

2022-05-10 12:08:34,041 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': ['interface loopback 1 ip address 2.2.2.2 255.255.255.255']} on 1 hosts
2022-05-10 12:08:35,627 - nornir.core.task -    ERROR -      start() - Host 'R2-CPE-BAT-A': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 269, in _load_candidate_wrapper
    tmp_file = self._create_tmp_file(source_config)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 244, in _create_tmp_file
    fobj.write(config)
TypeError: write() argument must be str, not list

2022-05-10 12:09:17,946 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': ['interface loopback 1 ip address 1.1.1.1 255.255.255.255']} on 1 hosts
2022-05-10 12:09:18,752 - nornir.core.task -    ERROR -      start() - Host 'R1-CPE-BAT-A': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 269, in _load_candidate_wrapper
    tmp_file = self._create_tmp_file(source_config)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 244, in _create_tmp_file
    fobj.write(config)
TypeError: write() argument must be str, not list

2022-05-10 12:09:18,758 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': ['interface loopback 1 ip address 2.2.2.2 255.255.255.255']} on 1 hosts
2022-05-10 12:09:20,658 - nornir.core.task -    ERROR -      start() - Host 'R2-CPE-BAT-A': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 269, in _load_candidate_wrapper
    tmp_file = self._create_tmp_file(source_config)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 244, in _create_tmp_file
    fobj.write(config)
TypeError: write() argument must be str, not list

2022-05-10 12:12:36,371 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': 'interface loopback 1 ip address 1.1.1.1 255.255.255.255'} on 1 hosts
2022-05-10 12:12:45,400 - nornir.core.task -    ERROR -      start() - Host 'R1-CPE-BAT-A': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 43, in napalm_configure
    device.commit_config()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 555, in commit_config
    raise MergeConfigException(merge_error)
napalm.base.exceptions.MergeConfigException: Configuration merge failed; automatic rollback attempted:

interface loopback 1 ip address 1.1.1.1 255.255.255.255
                     ^
% Invalid input detected at '^' marker.

55 bytes copied in 0.072 secs (764 bytes/sec)

2022-05-10 12:12:45,404 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': 'interface loopback 1 ip address 2.2.2.2 255.255.255.255'} on 1 hosts
2022-05-10 12:12:58,393 - nornir.core.task -    ERROR -      start() - Host 'R2-CPE-BAT-A': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 43, in napalm_configure
    device.commit_config()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 555, in commit_config
    raise MergeConfigException(merge_error)
napalm.base.exceptions.MergeConfigException: Configuration merge failed; automatic rollback attempted:

interface loopback 1 ip address 2.2.2.2 255.255.255.255
                     ^
% Invalid input detected at '^' marker.

55 bytes copied in 0.068 secs (809 bytes/sec)

2022-05-10 12:13:31,816 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': 'interface loopback 1 \n ip address 1.1.1.1 255.255.255.255'} on 1 hosts
2022-05-10 12:13:38,514 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': 'interface loopback 1 \n ip address 2.2.2.2 255.255.255.255'} on 1 hosts
2022-05-10 13:40:16,524 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': 'interface loopback 1 \n ip address 1.1.1.1 255.255.255.255 \n'} on 1 hosts
2022-05-10 13:40:23,194 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': 'interface loopback 1 \n ip address 2.2.2.2 255.255.255.255 \n'} on 1 hosts
2022-05-10 14:44:24,971 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': 'interface loopback 1 \n ip address 1.1.1.1 255.255.255.255 \n'} on 1 hosts
2022-05-10 14:44:31,733 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': 'interface loopback 1 \n ip address 2.2.2.2 255.255.255.255 \n'} on 1 hosts
2022-05-10 14:44:47,176 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['sh run']} on 6 hosts
2022-05-10 14:45:04,886 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['sh run']} on 6 hosts
2022-05-10 14:45:24,202 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['sh run']} on 6 hosts
2022-05-10 14:45:54,417 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['sh run']} on 6 hosts
2022-05-10 14:47:06,841 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['write']} on 6 hosts
2022-05-10 14:54:59,100 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'sh ip int brief'} on 4 hosts
2022-05-10 14:57:56,566 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'sh ip int brief'} on 4 hosts
2022-05-10 14:59:18,255 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface loopback 2 ', ' ip address 1.1.1.2 255.255.255.255']} on 1 hosts
2022-05-10 14:59:19,232 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface loopback 2 ', ' ip address 2.2.2.3 255.255.255.255']} on 1 hosts
2022-05-10 15:04:52,624 -  nornir.core -     INFO -        run() - Running task 'netmiko_save_config' with args {} on 6 hosts
2022-05-10 15:05:40,519 -  nornir.core -     INFO -        run() - Running task 'netmiko_save_config' with args {} on 4 hosts
2022-05-10 15:06:23,978 -  nornir.core -  WARNING -        run() - Task 'netmiko_save_config' has not been run â€“ 0 hosts selected
2022-05-10 15:06:32,973 -  nornir.core -  WARNING -        run() - Task 'netmiko_save_config' has not been run â€“ 0 hosts selected
2022-05-10 15:07:51,704 -  nornir.core -     INFO -        run() - Running task 'netmiko_save_config' with args {} on 2 hosts
2022-05-11 08:45:16,719 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/R1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 08:45:23,671 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/R2_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 08:45:34,554 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/R1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 08:45:39,592 - nornir.core.task -    ERROR -      start() - Host 'R1-CPE-BAT-B': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 283, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 626, in _scp_file
    return self._xfer_file(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 695, in _xfer_file
    raise CommandErrorException(msg)
napalm.base.exceptions.CommandErrorException: SCP file transfers are not enabled. Configure 'ip scp server enable' on the device.

2022-05-11 08:45:39,592 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/ESW1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 08:45:47,889 - nornir.core.task -    ERROR -      start() - Host 'ESW1-CPE-BAT-A': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 283, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 626, in _scp_file
    return self._xfer_file(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 695, in _xfer_file
    raise CommandErrorException(msg)
napalm.base.exceptions.CommandErrorException: SCP file transfers are not enabled. Configure 'ip scp server enable' on the device.

2022-05-11 08:45:47,889 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/ESW1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 08:45:57,180 - nornir.core.task -    ERROR -      start() - Host 'ESW1-CPE-BAT-B': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 283, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 626, in _scp_file
    return self._xfer_file(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 695, in _xfer_file
    raise CommandErrorException(msg)
napalm.base.exceptions.CommandErrorException: SCP file transfers are not enabled. Configure 'ip scp server enable' on the device.

2022-05-11 08:45:57,181 -  nornir.core -     INFO -        run() - Running task 'netmiko_save_config' with args {} on 6 hosts
2022-05-11 08:49:47,156 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/R1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 08:49:52,799 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/R2_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 08:50:01,592 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/R1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 08:50:06,817 - nornir.core.task -    ERROR -      start() - Host 'R1-CPE-BAT-B': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 283, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 626, in _scp_file
    return self._xfer_file(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 695, in _xfer_file
    raise CommandErrorException(msg)
napalm.base.exceptions.CommandErrorException: SCP file transfers are not enabled. Configure 'ip scp server enable' on the device.

2022-05-11 08:50:06,819 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/R2_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 08:50:12,394 - nornir.core.task -    ERROR -      start() - Host 'R2-CPE-BAT-B': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 283, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 626, in _scp_file
    return self._xfer_file(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 695, in _xfer_file
    raise CommandErrorException(msg)
napalm.base.exceptions.CommandErrorException: SCP file transfers are not enabled. Configure 'ip scp server enable' on the device.

2022-05-11 08:50:12,395 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/ESW1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 08:50:19,361 - nornir.core.task -    ERROR -      start() - Host 'ESW1-CPE-BAT-A': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 283, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 626, in _scp_file
    return self._xfer_file(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 695, in _xfer_file
    raise CommandErrorException(msg)
napalm.base.exceptions.CommandErrorException: SCP file transfers are not enabled. Configure 'ip scp server enable' on the device.

2022-05-11 08:50:19,361 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/ESW1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 08:50:26,475 - nornir.core.task -    ERROR -      start() - Host 'ESW1-CPE-BAT-B': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 283, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 626, in _scp_file
    return self._xfer_file(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 695, in _xfer_file
    raise CommandErrorException(msg)
napalm.base.exceptions.CommandErrorException: SCP file transfers are not enabled. Configure 'ip scp server enable' on the device.

2022-05-11 08:50:26,476 -  nornir.core -     INFO -        run() - Running task 'netmiko_save_config' with args {} on 6 hosts
2022-05-11 08:58:35,942 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/R1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 08:58:41,706 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/R2_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 08:58:50,663 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/R1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 08:59:02,989 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/R2_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 08:59:16,054 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/ESW1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 08:59:22,636 - nornir.core.task -    ERROR -      start() - Host 'ESW1-CPE-BAT-A': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 283, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 626, in _scp_file
    return self._xfer_file(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 695, in _xfer_file
    raise CommandErrorException(msg)
napalm.base.exceptions.CommandErrorException: SCP file transfers are not enabled. Configure 'ip scp server enable' on the device.

2022-05-11 08:59:22,637 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/ESW1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 08:59:47,760 -  nornir.core -     INFO -        run() - Running task 'netmiko_save_config' with args {} on 6 hosts
2022-05-11 09:00:06,190 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/R1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 09:00:11,606 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/R2_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 09:00:19,885 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/R1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 09:00:30,363 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/R2_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 09:00:41,117 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/ESW1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 09:01:04,525 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': './config/ESW1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 09:01:25,440 -  nornir.core -     INFO -        run() - Running task 'netmiko_save_config' with args {} on 6 hosts
2022-05-11 09:24:47,781 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': 'config/ESW1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 09:26:44,170 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/ESW1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 09:28:21,834 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': 'config/ESW1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 09:28:26,849 - nornir.core.task -    ERROR -      start() - Host 'ESW1-CPE-BAT-A': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/util.py", line 279, in retry_on_signal
    return function()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/base/base.py", line 86, in _netmiko_open
    self._netmiko_device = ConnectHandler(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/cisco/cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 350, in __init__
    self._open()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 355, in _open
    self.establish_connection()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 957, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 172.16.100.123:22



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 30, in napalm_configure
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/connections/__init__.py", line 57, in open
    connection.open()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 169, in open
    self.device = self._netmiko_open(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/base/base.py", line 95, in _netmiko_open
    raise ConnectionException("Cannot connect to {}".format(self.hostname))
napalm.base.exceptions.ConnectionException: Cannot connect to 172.16.100.123

2022-05-11 09:28:40,366 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': 'config/ESW1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 09:28:45,383 - nornir.core.task -    ERROR -      start() - Host 'ESW1-CPE-BAT-A': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/util.py", line 279, in retry_on_signal
    return function()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/base/base.py", line 86, in _netmiko_open
    self._netmiko_device = ConnectHandler(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/cisco/cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 350, in __init__
    self._open()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 355, in _open
    self.establish_connection()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 957, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 172.16.100.123:22



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 30, in napalm_configure
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_napalm/plugins/connections/__init__.py", line 57, in open
    connection.open()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/ios/ios.py", line 169, in open
    self.device = self._netmiko_open(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/napalm/base/base.py", line 95, in _netmiko_open
    raise ConnectionException("Cannot connect to {}".format(self.hostname))
napalm.base.exceptions.ConnectionException: Cannot connect to 172.16.100.123

2022-05-11 09:31:11,339 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': 'config/ESW1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 09:32:08,750 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'filename': 'config/ESW1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 09:34:32,100 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 09:34:33,585 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R2_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 09:34:39,013 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 09:34:45,579 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R2_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 09:34:52,461 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/ESW1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 09:35:00,468 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/ESW1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 09:35:10,913 -  nornir.core -     INFO -        run() - Running task 'netmiko_save_config' with args {} on 6 hosts
2022-05-11 09:36:41,401 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 09:36:42,786 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R2_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 09:36:47,923 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 09:36:54,075 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R2_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 09:37:01,254 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/ESW1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 09:37:09,686 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/ESW1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 09:37:19,066 -  nornir.core -     INFO -        run() - Running task 'netmiko_save_config' with args {} on 6 hosts
2022-05-11 10:50:18,364 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface loopback g2/0', 'sh']} on 1 hosts
2022-05-11 10:50:20,227 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'sh vrrp brief'} on 1 hosts
2022-05-11 10:50:20,484 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface loopback g2/0', 'no sh']} on 1 hosts
2022-05-11 10:50:21,076 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface loopback g2/0', 'sh']} on 1 hosts
2022-05-11 10:50:23,684 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'sh vrrp brief'} on 1 hosts
2022-05-11 10:50:24,145 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface loopback g2/0', 'no sh']} on 1 hosts
2022-05-11 10:51:28,491 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g2/0', 'sh']} on 1 hosts
2022-05-11 10:51:50,316 - nornir.core.task -    ERROR -      start() - Host 'R2-CPE-BAT-A': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 573, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 38, in netmiko_send_config
    result = net_connect.send_config_set(config_commands=config_commands, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1930, in send_config_set
    output += self.exit_config_mode()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/cisco_base_connection.py", line 54, in exit_config_mode
    return super().exit_config_mode(exit_config=exit_config, pattern=pattern)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1779, in exit_config_mode
    if self.check_config_mode():
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/cisco/cisco_ios.py", line 32, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/cisco_base_connection.py", line 38, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1740, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 583, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

2022-05-11 10:51:50,324 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'sh vrrp brief'} on 1 hosts
2022-05-11 10:51:50,325 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g2/0', 'no sh']} on 1 hosts
2022-05-11 10:51:50,326 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g3/0', 'sh']} on 1 hosts
2022-05-11 10:52:12,992 - nornir.core.task -    ERROR -      start() - Host 'R2-CPE-BAT-B': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 573, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 38, in netmiko_send_config
    result = net_connect.send_config_set(config_commands=config_commands, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1930, in send_config_set
    output += self.exit_config_mode()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/cisco_base_connection.py", line 54, in exit_config_mode
    return super().exit_config_mode(exit_config=exit_config, pattern=pattern)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 1783, in exit_config_mode
    output += self.read_until_pattern(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 583, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

2022-05-11 10:52:12,994 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'sh vrrp brief'} on 1 hosts
2022-05-11 10:52:12,995 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g3/0', 'no sh']} on 1 hosts
2022-05-11 10:52:50,857 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g2/0', 'sh']} on 1 hosts
2022-05-11 10:52:55,865 - nornir.core.task -    ERROR -      start() - Host 'R2-CPE-BAT-A': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/util.py", line 279, in retry_on_signal
    return function()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 28, in netmiko_send_config
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/cisco/cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 350, in __init__
    self._open()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 355, in _open
    self.establish_connection()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 957, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 172.16.100.126:22



2022-05-11 10:53:00,875 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'sh vrrp brief'} on 1 hosts
2022-05-11 10:53:00,876 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g2/0', 'no sh']} on 1 hosts
2022-05-11 10:53:00,876 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g3/0', 'sh']} on 1 hosts
2022-05-11 10:53:05,883 - nornir.core.task -    ERROR -      start() - Host 'R2-CPE-BAT-B': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/util.py", line 279, in retry_on_signal
    return function()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/paramiko/client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 28, in netmiko_send_config
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/cisco/cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 350, in __init__
    self._open()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 355, in _open
    self.establish_connection()
  File "/home/cpe/.local/share/virtualenvs/TP-03-D8SGa-7O/lib/python3.9/site-packages/netmiko/base_connection.py", line 957, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 172.16.100.190:22



2022-05-11 10:53:10,892 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'sh vrrp brief'} on 1 hosts
2022-05-11 10:53:10,893 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g3/0', 'no sh']} on 1 hosts
2022-05-11 10:56:15,395 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g2/0.10', 'sh', 'interface g2/0.20', 'sh']} on 1 hosts
2022-05-11 10:56:17,536 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'sh vrrp brief'} on 1 hosts
2022-05-11 10:56:17,817 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g2/0.10', 'sh', 'interface g2/0.20', 'no sh']} on 1 hosts
2022-05-11 10:56:18,552 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g3/0.10', 'sh', 'interface g3/0.20', 'sh']} on 1 hosts
2022-05-11 10:56:21,497 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'sh vrrp brief'} on 1 hosts
2022-05-11 10:56:21,872 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g3/0.10', 'sh', 'interface g3/0.20', 'no sh']} on 1 hosts
2022-05-11 10:56:43,905 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g2/0.10', 'sh', 'interface g2/0.20', 'sh']} on 1 hosts
2022-05-11 10:56:47,891 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'sh vrrp brief'} on 1 hosts
2022-05-11 10:56:48,171 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g2/0.10', 'sh', 'interface g2/0.20', 'no sh']} on 1 hosts
2022-05-11 10:56:48,893 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g3/0.10', 'sh', 'interface g3/0.20', 'sh']} on 1 hosts
2022-05-11 10:56:53,487 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'sh vrrp brief'} on 1 hosts
2022-05-11 10:56:53,854 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g3/0.10', 'sh', 'interface g3/0.20', 'no sh']} on 1 hosts
2022-05-11 10:57:03,710 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g2/0.10', 'sh', 'interface g2/0.20', 'sh']} on 1 hosts
2022-05-11 10:57:10,638 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'sh vrrp brief'} on 1 hosts
2022-05-11 10:57:10,925 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g2/0.10', 'sh', 'interface g2/0.20', 'no sh']} on 1 hosts
2022-05-11 10:57:11,577 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g3/0.10', 'sh', 'interface g3/0.20', 'sh']} on 1 hosts
2022-05-11 10:57:19,322 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'sh vrrp brief'} on 1 hosts
2022-05-11 10:57:19,665 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g3/0.10', 'sh', 'interface g3/0.20', 'no sh']} on 1 hosts
2022-05-11 10:57:40,593 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g2/0.10', 'sh', 'interface g2/0.20', 'sh']} on 1 hosts
2022-05-11 10:57:52,674 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'sh vrrp brief'} on 1 hosts
2022-05-11 10:57:52,924 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g2/0.10', 'sh', 'interface g2/0.20', 'no sh']} on 1 hosts
2022-05-11 10:57:53,649 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g3/0.10', 'sh', 'interface g3/0.20', 'sh']} on 1 hosts
2022-05-11 10:58:06,426 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'sh vrrp brief'} on 1 hosts
2022-05-11 10:58:06,761 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g3/0.10', 'sh', 'interface g3/0.20', 'no sh']} on 1 hosts
2022-05-11 11:00:00,913 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g2/0.10', 'sh', 'interface g2/0.20', 'sh']} on 1 hosts
2022-05-11 11:00:22,583 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'sh vrrp brief'} on 1 hosts
2022-05-11 11:00:22,835 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g2/0.10', 'sh', 'interface g2/0.20', 'no sh']} on 1 hosts
2022-05-11 11:00:23,620 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g3/0.10', 'sh', 'interface g3/0.20', 'sh']} on 1 hosts
2022-05-11 11:00:46,246 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'sh vrrp brief'} on 1 hosts
2022-05-11 11:00:46,639 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface g3/0.10', 'sh', 'interface g3/0.20', 'no sh']} on 1 hosts
2022-05-11 11:51:04,961 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': 'interface loopback 1 \n ip address 1.1.1.1 255.255.255.255 \n'} on 1 hosts
2022-05-11 11:51:11,693 -  nornir.core -     INFO -        run() - Running task 'napalm_configure' with args {'configuration': 'interface loopback 1 \n ip address 2.2.2.2 255.255.255.255 \n'} on 1 hosts
2022-05-11 11:51:22,355 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['write']} on 6 hosts
2022-05-11 11:51:27,858 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 11:51:29,526 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R2_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 11:51:34,843 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 11:51:40,923 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/R2_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 11:51:47,845 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/ESW1_CPE_LYON_BAT_A.conf'} on 1 hosts
2022-05-11 11:51:55,345 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_file': 'config/ESW1_CPE_LYON_BAT_B.conf'} on 1 hosts
2022-05-11 11:52:04,339 -  nornir.core -     INFO -        run() - Running task 'netmiko_save_config' with args {} on 6 hosts
2022-05-11 17:27:30,984 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['router ospf 1', 'network 172.16.10.0 0.0.0.255 area 0', 'network 172.16.20.0 0.0.0.255 area 0']} on 2 hosts
2022-05-11 17:27:33,101 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['router ospf 1', 'network 172.16.30.0 0.0.0.255 area 0', 'network 172.16.40.0 0.0.0.255 area 0']} on 2 hosts
2022-05-11 17:30:00,249 -  nornir.core -     INFO -        run() - Running task 'netmiko_save_config' with args {} on 6 hosts
